### ISSUE TITLE
Create lobby to create or find a game on the internet

### ISSUE THREAD

**Issue by Potrunks** [Potrunks/elemental-fighter#152]
- [ ] From the main menu, create multiplayer button
- [ ] Create a lobby scene
- [ ] Create UI with join and create game
- [ ] Create UI for create game (game name, game ID...)
- [ ] Create button allow to go character selection with multiplayer game initialized
- [ ] Create UI for join game (display all available game)
- [ ] Create button to accept to join a game
