### ISSUE TITLE
Implement script for character selection during multiplayer mode

### ISSUE THREAD

**Issue by Potrunks** [Potrunks/elemental-fighter#153]
- [ ] Allow new player to connect
- [ ] Allow players to move in character selection scene (sync)
- [ ] Allow players to choose character
- [ ] Allow the host to start the game when all players choose a character
- [ ] Add a timer during character selection, after timer, if players have no character, it's random choice
