### ISSUE TITLE
Implement script for a game during multiplayer mode

### ISSUE THREAD

**Issue by Potrunks** [Potrunks/elemental-fighter#154]
- [ ] Create script for fighting in multiplayer mode synchronized
- [ ] Apply settings multiplayer mode
- [ ] Endgame management (retry, quit...)
